# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'livereload' do
  watch(%r{src/.+\.(html|js)})
  watch(%r{assets/.+\.(css|js|html)})
end

guard 'sass', :input => 'assets/styles/sass', :output => 'assets/styles/css'

guard 'compass' do
  watch('^src/(.*)\.s[ac]ss')
end
